### ISSUE TITLE
啥时候支持规则引擎

### ISSUE THREAD

**Issue by darcyg** [wind-c/comqtt#11]
最近在找支持规则引擎的mqtt项目
目前有的是emqx旗下的3款，最近在考虑ekuiper
不过都是基于sql的.逻辑不太清晰
不知道这个项目的规则引擎准备怎么做。
建议用 https://github.com/hyperjumptech/grule-rule-engine 这类 DSL
如果开始规则引擎代码之后。我计划也添砖加瓦一下，贡献一点想法和代码
PS。我还没学GO。等你们开工了，我跟着一边学GO

**Comment by wind-c** [comment]
规则引擎是接下来的开发重点，已经着手研究

**Comment by darcyg** [comment]
> 规则引擎是接下来的开发重点，已经着手研究

什么时候可以放出代码？
另外强烈建议可以定义虚拟设备。就是内存中虚拟一个或多个设备（支持多个属性）
ekuiper里面是内存表的东西。

**Comment by wind-c** [comment]
Mqtt broker到Kafka的桥接能力已经支持，可以配置一定的规则来转发消息，初步具备规则引擎的能力。
