### ISSUE TITLE
请问什么时候能支持MQTT Bridge？

### ISSUE THREAD

**Issue by DarkiT** [wind-c/comqtt#13]
请问什么时候能支持MQTT Bridge？

**Comment by skygp** [comment]
这个用集群就行了

**Comment by wind-c** [comment]
桥接一般用规则引擎按规则把指定message转发到其它mqtt broker、Kafka、其它MQ或存储到DB和NoSQL等，目前在规划研究阶段，是接下来的开发重点。

**Comment by wind-c** [comment]
Bridge is supported in version 2.0
