### ISSUE TITLE
消息最大支持长度问题

### ISSUE THREAD

**Issue by ahthabc** [wind-c/comqtt#24]
设置了BufferSize，BufferBlockSize，消息过大时，在下图所在位置报错
![image](https://user-images.githubusercontent.com/45655409/207556289-af9cd7ed-be78-4b5f-8c43-b599c0c79037.png)

**Comment by wind-c** [comment]
2.0版本解决

**Comment by skygp** [comment]
> 
wind-c, 请问大概什么时候会发2.0版本呢？

**Comment by wind-c** [comment]
在已经发布的2.0版已解决
