### ISSUE TITLE
问题 

### ISSUE THREAD

**Issue by cexll** [wind-c/comqtt#3]
1. 项目会长期维护吗
2. 项目和 https://github.com/mochi-co/mqtt readme内数据高度相似是为啥
```
Mochi | Mosquitto | EMQX | VerneMQ | Mosca
-- | -- | -- | -- | --
SEND Max | 36505 | 30597 | 27202 | 32782 | 30125
```
3. comqtt 和 mochi-co/mqtt 有什么关联吗

**Comment by cqcsdzmt** [comment]
哈哈哈，我猜应该是在mochi-co/mqtt的基础上多了集群的支持吧。

我简单测了下，集群模式有bug，设备上线一会就再也上不了线了，必须得重启broker

**Comment by cexll** [comment]
> 哈哈哈，我猜应该是在mochi-co/mqtt的基础上多了集群的支持吧。
> 
> 我简单测了下，集群模式有bug，设备上线一会就再也上不了线了，必须得重启broker

你为什么消息接受的这么快

**Comment by cqcsdzmt** [comment]
> 哈哈哈，我猜应该是在mochi-co/mqtt的基础上多了集群的支持吧。
> 
> 我简单测了下，集群模式有bug，设备上线一会就再也上不了线了，必须得重启broker

集群那块我有个疑问，为啥上线和发布可以通过gossip同步，为啥订阅和取消订阅却要用raft包一层？

**Comment by cqcsdzmt** [comment]
> > 哈哈哈，我猜应该是在mochi-co/mqtt的基础上多了集群的支持吧。
> > 我简单测了下，集群模式有bug，设备上线一会就再也上不了线了，必须得重启broker
> 
> 你为什么消息接受的这么快

这叫缘分吧

**Comment by cexll** [comment]
> > > 哈哈哈，我猜应该是在mochi-co/mqtt的基础上多了集群的支持吧。
> > > 我简单测了下，集群模式有bug，设备上线一会就再也上不了线了，必须得重启broker
> > 
> > 
> > 你为什么消息接受的这么快
> 
> 这叫缘分吧

0.0 hh

**Comment by wind-c** [comment]
> 1. 项目会长期维护吗
> 2. 项目和 https://github.com/mochi-co/mqtt readme内数据高度相似是为啥
> ```
> Mochi | Mosquitto | EMQX | VerneMQ | Mosca
> -- | -- | -- | -- | --
> SEND Max | 36505 | 30597 | 27202 | 32782 | 30125
> ```
> 3. comqtt 和 mochi-co/mqtt 有什么关联吗

是以mochi-co/mqtt为基础建立的项目，添加了集群支持、mqttv5.0支持和Auth/ACL插件

**Comment by wind-c** [comment]
> 哈哈哈，我猜应该是在mochi-co/mqtt的基础上多了集群的支持吧。
> 
> 我简单测了下，集群模式有bug，设备上线一会就再也上不了线了，必须得重启broker

可以详细描述一下问题吗？

**Comment by wind-c** [comment]
> > 哈哈哈，我猜应该是在mochi-co/mqtt的基础上多了集群的支持吧。
> > 
> > 我简单测了下，集群模式有bug，设备上线一会就再也上不了线了，必须得重启broker
> 
> 集群那块我有个疑问，为啥上线和发布可以通过gossip同步，为啥订阅和取消订阅却要用raft包一层？

raft解决分布式数据一致性问题，各节点的订阅树和路由表要保持一致，这样publish消息才能路由到订阅者所在节点。gossip解决分布式节点发现和把需要同步的订阅及取消订阅数据发到raft leader执行写操作。

**Comment by cexll** [comment]
大佬项目会长期维护吗

**Comment by wind-c** [comment]
> 大佬项目会长期维护吗
> 
当然，也欢迎提bug、发展建议和贡献代码

**Comment by cexll** [comment]
有几个问题请大佬解答一下
1. 我应该怎么做才能通过server指定 id 来发送消息
2. 我应该怎么做才能通过server向主题发送消息
3. 如何扩展http或ws的功能

**Comment by wind-c** [comment]
1.向指定clientid发消息不符合mqtt协议规范，每个客户端以自己的id为topic订阅
2.向指定topic发消息，看Server#Publish方法
3.扩展http功能，可参考cmd/cluster/main.go 185行

**Comment by cexll** [comment]
> 1.向指定clientid发消息不符合mqtt协议规范，可以每个客户端以自己的id为topic订阅
> 2.向指定topic发消息，看Server#Publish方法
> 3.扩展http功能，可参考cmd/cluster/main.go 185行

感谢大佬回答 我已经找到第二问题的方法 
第一个问题我找了下其他方案也确实都没有支持
