### ISSUE TITLE
server.Events.OnSubscribe, 加入订阅是没有打印信息

### ISSUE THREAD

**Issue by Hayast** [wind-c/comqtt#35]
在main.go里加了server.Events.OnSubscribe
// Add OnSubscribe Event Hook
	server.Events.OnSubscribe = func(filter string, cl events.Client, qos byte, isFirst bool) {
		fmt.Printf("<< OnSubscribe client subscribed %s: %s %d %t \n", cl.ID, filter, qos, isFirst)
	}
客户端订阅主题的时候没有打印出信息?

有例子参考是如何使用subscribe吗?  客户端接收不到订阅的主题.

**Comment by Hayast** [comment]
![1680576693798](https://user-images.githubusercontent.com/111619181/229674733-2bd1285a-bcd9-40ef-80c6-e8b42c5d6990.png)

**Comment by Hayast** [comment]
server.Events.OnMessage = func(cl events.Client, pk events.Packet) (pkx events.Packet, err error) 
这里有打印信息
如图

**Comment by wind-c** [comment]
是集群模式接不到消息吗？看你的代码是1.x版本的，建议升级到2.0

**Comment by Hayast** [comment]
升级到了2版本, 订阅出现 Subscribe Failed Unexpected QoS, SubACK failed, Please check MQTT broker ACL configuration, 
要如何设置?
![image](https://user-images.githubusercontent.com/111619181/230292890-8f15909d-b8e0-4342-b70d-e754e7f666ae.png)

**Comment by Hayast** [comment]
auth-mode: 1  # 0 Anonymous, 1 Username, 2 ClientID
acl-mode: 0  # 0 Anonymous, 1 Username, 2 ClientID

acl-mode:  设0可以,
