### ISSUE TITLE
Persist messages to kafka

### ISSUE THREAD

**Issue by perbu** [wind-c/comqtt#44]
Hello.

We're considering adding support to persist all MQTT topic matching a certain filter, to Kafka. Not sure if this is relevant for the project. If it is relevant for the project, let me know and we'll work together as we implement it according to your guidelines.

If not, which is perfectly fine, we'll just do it in a private fork.

All the best, 

Per.

**Comment by wind-c** [comment]
Bridging messages to kafka is already supported, see plugin/bridge/kafka.
If you find any problems or need to add any capabilities, please report back.

**Comment by perbu** [comment]
that was funny. thanks for pointing me the right way.
