### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by perbu** [wind-c/comqtt#46]
Hi.
I've been spending some more time in the code base and I have a couple of suggestions. I'm offering to help here if we want to do this:

1) Protect the main branch and have all development go through PRs. The main reason for this is:
2) Have github refuse to merge PRs that have failing tests.

Having failing tests in main for more than a few hours is not a great look and also makes it really hard to work on the codebase.

Before implementing this the tests need to be all green, though. I'll see what I can do, I'm new to the codebase and I'm not always sure what the issue is.

All the best,

Per.

**Comment by wind-c** [comment]
Great advice.Due to time constraints and limited contributors, the test cases are incomplete. You are welcome to join us and we will work together to improve it.

**Comment by perbu** [comment]
I know how it is. I'll help get the test suite green again. Once we're done with that we could see what else we need to do. Overall, I think things are very good. Well done.

I'm not working until mid August, so my contributions will be limited until then.

Cheers.
