### ISSUE TITLE
Use of Init to launch http server.

### ISSUE THREAD

**Issue by perbu** [wind-c/comqtt#61]
In both the single and cluster main() there are web servers started in init() on port 6060.

This complicates thing when testing as there no easy way to shut the server down again. The server responds with a 404 and disabling it doesn't seem to affect the server. 

Are you ok with removing this?

**Comment by wind-c** [comment]
This :6060 is for pprof. I think to use a configuration parameter to turn it on or off.

**Comment by perbu** [comment]
I'll cook something up.

**Comment by perbu** [comment]
Right. Didn't really find a better way to do it. I just left it.
