### ISSUE TITLE
Enable "hacktoberfest" contributions?

### ISSUE THREAD

**Issue by asbjorn** [wind-c/comqtt#74]
Hi!

Can we either add the topic "hacktoberfest" or add the PR label "hacktoberfest-accepted" to attract contributions during the global "hacktoberfest" movement?

**Comment by asbjorn** [comment]
What do you think @wind-c ?

**Comment by asbjorn** [comment]
Hi!

So - hacktoberfest (https://hacktoberfest.com) is a arranged every October, and the objective is for all of its participants to contribute to opensource projects on github and gitlab. In order for each contribution to count the projects either needs to "opt-in" by add the topic "hacktoberfest" or add the PR label "hacktoberfest-accepted" so that if a PR is approved the contribution is attributed to the person who created it.

Clear instructions of project maintainers are described here: https://hacktoberfest.com/participation/#maintainers It's very easy and it opens the project up for more contributions.

**Comment by wind-c** [comment]
I've added the hacktoberfest tag for comqtt.

Thanks!
