### ISSUE TITLE
queue/retry messages to Kafka

### ISSUE THREAD

**Issue by fcrbat** [wind-c/comqtt#88]
Hi,
is there way to queue/retry messages sent to kafka if the broker isn't available?

**Comment by wind-c** [comment]
Comqtt can send messages from the Broker to Kafka, but cannot send messages if the Broker is unavailable.

So, what are your specific application scenarios?

**Comment by fcrbat** [comment]
Lets say the broker is unvailable for a few minutes, is there a way to queue/retry the messages?

**Comment by fcrbat** [comment]
Found another way
