### ISSUE TITLE
Redis: Usage of old go-redis package, before go-redis received official support by Redis

### ISSUE THREAD

**Issue by jaxtonw** [wind-c/comqtt#91]
Currently, we're using `go-redis/redis` at [version 8.11.5](https://github.com/wind-c/comqtt/blob/e5224574ba7338a4e498e2c63706a55086c149e1/go.mod#L9). This package has moved namespaces and upgraded to version 9, ever since Redis officially supported it as a Redis client.

https://redis.io/blog/go-redis-official-redis-client/

We should update our used Redis package to the officially supported client at the new namespace: https://github.com/redis/go-redis

**Comment by wind-c** [comment]
Got it. I will update to the new namespace(https://github.com/redis/go-redis) as soon as possible.

**Comment by wind-c** [comment]
Changed in v2.5.6.

**Comment by jaxtonw** [comment]
Thanks so much for taking care of this!
