### ISSUE TITLE
Include cmd/cluster in Dockerfile

### ISSUE THREAD

**Issue by ohkinozomu** [wind-c/comqtt#95]
Hello,

I noticed that the Dockerfile does not include cmd/cluster.
Is there any consideration for creating a Dockerfile that includes cmd/cluster?

Option 1:
Include cmd/cluster in the current Dockerfile. In this case, the size increases from 15.6 MB to 32.8 MB.

Option 2:
Create a separate Dockerfile, for example, `Dockerfile.cluster`.

Which option is preferable?
I prefer Option 1, but if size is an issue, Option 2 should be considered.

**Comment by wind-c** [comment]
Why such a big difference in size?

**Comment by ohkinozomu** [comment]
Sorry, I was referring to the `Virtual size` value in [Google Artifact Registry](https://cloud.google.com/artifact-registry), which is defined as "Compressed total image size to be downloaded over the network." This seems to be different from the local container image size. 

Here are the actual details:

```
REPOSITORY       TAG               IMAGE ID       CREATED         SIZE
comqtt-tobe      latest            b44b748866c6   4 seconds ago   69.8MB
comqtt-current   latest            e0d5e6f60bcf   3 minutes ago   33.1MB
```

The difference is simply the binary size of comqtt-cluster.

```
/ # ls -alh
......
-rwxr-xr-x    1 root     root       24.1M Jul 25 22:28 comqtt
-rwxr-xr-x    1 root     root       35.0M Jul 25 22:29 comqtt-cluster
```

The Dockerfile I created is as shown in https://github.com/wind-c/comqtt/pull/96
